### ISSUE TITLE
how to generate fixed weights for FBF

### ISSUE THREAD

**Issue by yuan9778** [fakufaku/pyramic-demo#2]
Hello there,

In pyramic-demo project, I wonder how you generate the  fixed_weights which are stored in a json file. Thanks much!

**Comment by fakufaku** [comment]
Hi @yuan9778 ! For the purpose of the demo, we had a trick! We did a calibration step prior to the demo to obtain the steering vector weights from the target source.

The file `demos/demo_gsc_calibration.cpp` contains the source code for the calibration step. Essentially we compute the spatial covariance matrix in the STFT domain and then compute the dominant eigenvector at the end. We assume that only the target source is active during calibration.

**Comment by yuan9778** [comment]
This helps a lot. Thanks Robin.
